### PR TITLE
feat: add --inline flag

### LINKED ISSUE #55: feat: gotouch should be able to create files in the current directory
## Use case

I'd like to use `gotouch` not only to bootstrap complete projects but also to distribute common default files like:

- .gitignore
- .editorconfig
- ...

currently `gotouch` always creates a directory with the name of the module requiring the user to move the template file a level up and delete the created directory.

## Possible solutions

- introduce a flag to create files in specified directory instead of creating a new one
- introduce some kind of 'project type' and differentiate between:
    - module template
    - file template

having different kinds of project types moves the control to the properties YAML author which sounds like from an author perspective and potentially annoying from a user perspective :smile: 

Same as already mentioned in the previous issue, as soon as the details are settled I'd be happy to provide you with a PR as well!

### PR DESCRIPTION
**Pull request by baez90**
# What does this PR change?

Add a flag that allows the user to apply the selected template to the current working directory instead of newly created subdirectory

Resolves #55

### CODE REVIEW

**Comment by baez90** [comment]
I updated all tests to make them pass again, I'm not sure if I shall add some tests?

Initially I tried to pass the flag along the call chain but at some point I realized using the `store.Store` would be a lot easier. I hope this matches your architecture/concept as well? Add an `Inline` field to every struct in the call chain felt a little bit repetitive which is why I went for the `store.Store` approach.
I did some manual testing if the behavior is as expected and it seemed to be alright 😊

I replaced some `fmt.Sprintf()` calls that were used to construct new paths with `filepath.Join()` I hope you don't mind, I couldn't think of a good reason not to use function from the standard library, but I can revert it if you prefer?

**Comment by denizgursoy** [comment]
I tested it and it worked perfectly fine. Can you also add a test to internal/integration/integration_test.go file?

**Comment by baez90** [comment]
I'm working on it, not 100% sure why, some tests that shouldn't be affected at all are failing but I'll update the PR as soon as I'm finished adding a test and rebasing the branch after the previous merge

**Comment by baez90** [comment]
I added the integration test and rebased the branch.
I hope you don't mind me replacing the `fmt.Sprintf()` with `filepath.Join()` where applicable because at some point I'd probably like to use `gotouch` also from Windows and then the hardcoded `/` could become a problem 😅 
I also replaced some custom code with existing helpers from testify e.g. to check for errors/no errors because the helpers print nice messages with details about the error and such 😉

**Comment by denizgursoy** [comment]
I merged it but pipeline failed. I am working on it (https://github.com/denizgursoy/gotouch/actions/runs/6449156925/job/17507168368)

**Comment by denizgursoy** [comment]
I fixed the tests and created the version 1.15.0. Thank you for your contribution. I want to update Gotouch's website to add documentation about `--inline` flag and `.netrc` authentication

**Comment by baez90** [comment]
I'm sorry that there were some test failures I didn't notice 😕 I enabled the pipelines to run in my fork as well for now. Probably running the pipelines as PR check could help as well?
Thanks for taking care!

**Pull request merged**
